name = "gemini-python-backend" # Choose a name for your worker
main = "worker.py"            # The entrypoint for your code
compatibility_date = "2024-05-01"

[build]
command = "pip install -r requirements.txt"