name = "gemini-python-backend"
main = "worker.py"
compatibility_date = "2024-05-01"
compatibility_flags = ["python_workers"]

[build]
command = "pip install -r requirements.txt"
upload.format = "python"
upload.main = "worker.py"
